//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChoDoCuEntities : DbContext
    {
        public ChoDoCuEntities()
            : base("name=ChoDoCuEntities")
        {
            // Tắt validation để cho phép thêm entities mới không có trong EDMX
            this.Configuration.ValidateOnSaveEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // Không throw exception để cho phép thêm entities thủ công
        }
    
        public virtual DbSet<Category_Product> Category_Product { get; set; }
        public virtual DbSet<Category_Status> Category_Status { get; set; }
        public virtual DbSet<Comment_Product> Comment_Product { get; set; }
        public virtual DbSet<infoAccount> infoAccounts { get; set; }
        public virtual DbSet<listOrder> listOrders { get; set; }
        public virtual DbSet<listSell> listSells { get; set; }
        public virtual DbSet<listShip> listShips { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
