//------------------------------------------------------------------------------
// <auto-generated>
//     Warehouse Management Models
//     Created: 2025-11-15
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class InventoryHistory
    {
        public int idHistory { get; set; }
        
        [Required]
        public int idProduct { get; set; }
        
        [Required]
        public int idSeller { get; set; }
        
        [Required]
        public System.DateTime changeDate { get; set; }
        
        [Required]
        [StringLength(20)]
        public string changeType { get; set; }
        
        [Required]
        public int quantityBefore { get; set; }
        
        [Required]
        public int quantityChange { get; set; }
        
        [Required]
        public int quantityAfter { get; set; }
        
        [StringLength(20)]
        public string referenceType { get; set; }
        
        public Nullable<int> referenceId { get; set; }
        
        [StringLength(300)]
        public string notes { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Login Seller { get; set; }
    }
}
