//------------------------------------------------------------------------------
// <auto-generated>
//     Warehouse Management Models
//     Created: 2025-11-15
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class InventorySummary
    {
        public int idSummary { get; set; }
        
        [Required]
        public int idProduct { get; set; }
        
        [Required]
        public int idSeller { get; set; }
        
        [Required]
        public int currentStock { get; set; }
        
        [Required]
        public System.DateTime lastUpdated { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Login Seller { get; set; }
    }
}
