//------------------------------------------------------------------------------
// <auto-generated>
//     Warehouse Management Models
//     Created: 2025-11-15
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Stocktake
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stocktake()
        {
            this.StocktakeDetails = new HashSet<StocktakeDetail>();
        }
    
        public int idStocktake { get; set; }
        
        [Required]
        public int idSeller { get; set; }
        
        [Required]
        [StringLength(20)]
        public string stocktakeCode { get; set; }
        
        [Required]
        public System.DateTime stocktakeDate { get; set; }
        
        [Required]
        [StringLength(20)]
        public string status { get; set; }
        
        [Required]
        public int totalProductsChecked { get; set; }
        
        [Required]
        public int totalDiscrepancy { get; set; }
        
        [StringLength(500)]
        public string notes { get; set; }
        
        [Required]
        public int createdBy { get; set; }
        
        public Nullable<System.DateTime> completedDate { get; set; }
    
        public virtual Login Seller { get; set; }
        public virtual Login Creator { get; set; }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StocktakeDetail> StocktakeDetails { get; set; }
    }
}
