//------------------------------------------------------------------------------
// <auto-generated>
//     Warehouse Management Models
//     Created: 2025-11-15
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class StocktakeDetail
    {
        public int idStocktakeDetail { get; set; }
        
        [Required]
        public int idStocktake { get; set; }
        
        [Required]
        public int idProduct { get; set; }
        
        [Required]
        public int systemQuantity { get; set; }
        
        [Required]
        public int actualQuantity { get; set; }
        
        // Computed column - tính tự động
        public int discrepancy { get; set; }
        
        [StringLength(300)]
        public string reason { get; set; }
        
        [Required]
        public bool isAdjusted { get; set; }
        
        [StringLength(300)]
        public string notes { get; set; }
    
        public virtual Stocktake Stocktake { get; set; }
        public virtual Product Product { get; set; }
    }
}
