//------------------------------------------------------------------------------
// <auto-generated>
//     Warehouse Management Models
//     Created: 2025-11-15
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class WarehouseReceiptDetail
    {
        public int idReceiptDetail { get; set; }
        
        [Required]
        public int idReceipt { get; set; }
        
        [Required]
        public int idProduct { get; set; }
        
        [Required]
        public int quantity { get; set; }
        
        [StringLength(50)]
        public string condition { get; set; }
        
        [StringLength(300)]
        public string notes { get; set; }
    
        public virtual WarehouseReceipt WarehouseReceipt { get; set; }
        public virtual Product Product { get; set; }
    }
}
