//------------------------------------------------------------------------------
// <auto-generated>
//     Warehouse Management Models
//     Created: 2025-11-15
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class WarehouseIssue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WarehouseIssue()
        {
            this.WarehouseIssueDetails = new HashSet<WarehouseIssueDetail>();
        }
    
        public int idIssue { get; set; }
        
        [Required]
        public int idSeller { get; set; }
        
        [Required]
        [StringLength(20)]
        public string issueCode { get; set; }
        
        [Required]
        public System.DateTime issueDate { get; set; }
        
        [Required]
        [StringLength(50)]
        public string issueType { get; set; }
        
        public Nullable<int> idOrder { get; set; }
        
        public Nullable<int> idBuyer { get; set; }
        
        [Required]
        public int totalQuantity { get; set; }
        
        [StringLength(300)]
        public string reason { get; set; }
        
        [Required]
        public int createdBy { get; set; }
        
        [Required]
        [StringLength(20)]
        public string status { get; set; }
    
        public virtual Login Seller { get; set; }
        public virtual Order Order { get; set; }
        public virtual Login Buyer { get; set; }
        public virtual Login Creator { get; set; }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseIssueDetail> WarehouseIssueDetails { get; set; }
    }
}
