//------------------------------------------------------------------------------
// <auto-generated>
//     Warehouse Management Models
//     Created: 2025-11-15
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class WarehouseReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WarehouseReceipt()
        {
            this.WarehouseReceiptDetails = new HashSet<WarehouseReceiptDetail>();
        }
    
        public int idReceipt { get; set; }
        
        [Required]
        public int idSeller { get; set; }
        
        [Required]
        [StringLength(20)]
        public string receiptCode { get; set; }
        
        [Required]
        public System.DateTime receiptDate { get; set; }
        
        [Required]
        [StringLength(50)]
        public string receiptType { get; set; }
        
        [StringLength(200)]
        public string supplierInfo { get; set; }
        
        [StringLength(500)]
        public string notes { get; set; }
        
        [Required]
        public int totalQuantity { get; set; }
        
        [Required]
        public int createdBy { get; set; }
        
        [Required]
        [StringLength(20)]
        public string status { get; set; }
    
        public virtual Login Seller { get; set; }
        public virtual Login Creator { get; set; }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseReceiptDetail> WarehouseReceiptDetails { get; set; }
    }
}
